### ISSUE TITLE
DEV style events page, add to calendar button

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#13]
Only future events show, add to calendar, no ticket buying.

**Comment by JuliaDickey** [comment]
Fixed layout, but still fixing add to calendar widget

**Comment by kelseyfriedman** [comment]
I see there is a bug for the add to calendar thing. 

I can't properly QA this until the Admin Dashboard is working because I need to change dates to test the functionality. Leaving here until I can check

**Comment by kelseyfriedman** [comment]
- [ ] I changed the date to a past date and it's still showing up. They should not appear if they are in the past.

**Comment by JuliaDickey** [comment]
I added a filter so past date events won't show up on the /events page,  and they're sorted by date. On Admin I updated the time to match the other format, and past events will still show up so they can be deleted.

**Comment by kelseyfriedman** [comment]
This is great. I'm making an issue for you to remove all placeholder events before we go live but I think we should leave them for now to show Ashley in your meeting and then delete them.

**Comment by kelseyfriedman** [comment]
Actually... i have to re-open this. I QAd this on on iPhone6 and the addtocalendar link doesn't work. When I click google calendar it opens my calendar but without the create event page and when i click ical i get the below screenshot
![img_5564](https://cloud.githubusercontent.com/assets/3065594/23849217/c5ceda28-07eb-11e7-9f97-77c073e2c8f6.PNG)

**Comment by JuliaDickey** [comment]
I did some digging, and this doesn't work on mobile. Google doesn't allow you to add Events through outside variables unless it's desktop or tablet. I hid the buttons for mobile. I'm not sure what the ultimate solve is for this.

**Comment by kelseyfriedman** [comment]
Cool, totally fine hiding on mobile for now. We won't have that many events anyway
