### ISSUE TITLE
Fix Admin Dashboard forms

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#21]
From Julia:
Don't add anything through the admin dash yet. Forms are not all working, and I want to keep the one version of the database till we go live.

**Comment by JuliaDickey** [comment]
Everything is updated, and working with the exception of the blog. I'm adding that to the blog issue.

**Comment by kelseyfriedman** [comment]
I can't click any of the Update or Add links so I can't test this yet

**Comment by JuliaDickey** [comment]
Working on fixing blog update/add. The text editor has a conflict with Boostrap. Everything else is working. Added subnav to limit endless scrolling on the page.

**Comment by JuliaDickey** [comment]
Fixed it!

**Comment by kelseyfriedman** [comment]
I can't access the Admin db at all

**Comment by JuliaDickey** [comment]
I precompiled. It works on intense spire now.

**Comment by kelseyfriedman** [comment]
Yayyyy I can do stuff!!! I'm still noticing a few problems here. 

- [ ] Love the new drop down menu! So helpful. Should we move "Add blog post" from the utility nav into that menu? I don't think we'll be blogging enough to need it up in the main area. 
- [ ] I tried to update the students because I think the job titles (pilot and physics teacher) should be lowercase. I was able to open the modal, but when I clicked update, nothing happened.
- [ ] Events are still 24 hour clock on admin dashboard - is that intentional? Not sure it matters too much but since we changed it on the front. 
- [ ] On jobs, when I clicked Update, the "Learn more about this position" link disappeared on more than one of the entries. It's still showing on the front end but I wanted to note this cause it's kind of odd behavior. 
- [ ] Math Teacher and Biology teacher use different language for the "No stipend" part? Not sure where that appears but noting it. 
- [ ] I didn't have time to test adding a new position or a new student. Maybe that's the activity you can do with Ashley in person since she is likely going to use those two sections (and events) a lot.

**Comment by JuliaDickey** [comment]
I put "Add blog post" in the top admin nav because there are two types of users: admin and bloggers. Bloggers can only add blog content. Admin can edit all content. If you want to remove blog-only users I can take it out of the nav and we can just have admin users.

**Comment by JuliaDickey** [comment]
-Fixed the link now showing. It was missing from the AJAX partial. 
-When you click update, there's must have been a glitch in the modal not hiding, but the database is updating. If you hit refresh the change shows up on the page. I'll check it next time I push. 
-Removed the stipend part, since we're not showing it on the Volunteer page. 
-Cool, I can check adding a new student and a position with Ashley when we meet.

**Comment by kelseyfriedman** [comment]
That makes sense! Let's leave blog up there in the nav for bloggers.

- [ ] I'm still having the issue with update students. After reading your note I updated all the job titles and saw they did change on the front end (and presumably the database) but they still don't show updated on the dashboard and the modal doesn't clear when I click update. 
- [ ] If you look at "testing the past events" even it's still 24 hour clock. I'm honestly not too worried about it but you said it was fixed so wanted to point it out.

**Comment by JuliaDickey** [comment]
-I've updated the 24 hour clock to a 12 hour clock on the event partial. 
-I'm having a conflict between my text editor and the bootstrap modal. If you hit the update button and the modal freezes, you can hit 'command r' to refresh the page, and it will show your update worked. I'm asking my mentor about this this week.

**Comment by kelseyfriedman** [comment]
Adding one more issues here - on the blog section in the admin dashboard, the dates don't all match up. The student selection story has a march date but the actual date in the post is february https://intense-spire-56347.herokuapp.com/admin#blog-posts-section

**Comment by JuliaDickey** [comment]
Done! That was a swirly one. The dates on the blog are updated, and the forms on the admin page are updated.
