### ISSUE TITLE
Update images across site 

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#3]
We have selected images for all the CTA banners all labeled CTABanner_Name and and the 9 Causes on Campus labeled Cause_Name. I've also added a few extra photos in case you need some other to replace placeholders. Here is the link to Victoria's photos as well. There are some good campus and candid shots in here. https://drive.google.com/drive/folders/0BwZq6uti5T-_d0M4TDlzXy0xTk0

A couple notes:

- [x] The picture you are currently using in the CTA banner (Glory with the volunteer) can be the photo for the Blog CTA cause we didn't really have anything specific for that. 
- [x] The picture we found for Our Story CTA may not work in that small space. If that's the case, can you just pick a photo of a cute kid? 
- [x] As noted in the previous email, we repeat Our Story a lot in the banners, but with different text. I think we need to only have one Our Story banner so I added a photo for Volunteer and Sponsor a student in case you want to add those. Otherwise use them for other places?
- [x] Can you change the main header image on Our Focus to something else because we  need that photo for the solar powered CTA? 
- [x] Also we noticed that the same photos are being repeated twice on the lower part of Our Focus and they are blurry. Please use some of the photos we sent or those from Victoria's drive. 
- [x] It seems like there are some other placeholder images here that are blurry (like on Volunteer page). Can you please sweep through and make sure the images are all final and what you want? 

As far as the text on the School page, Jordan did a review and he actually sent over some edits that I need to reconcile. I will do that at the beginning of the week and send them over when I do my QA of your changes. 

Also an FYI, one of my projects here is to get a central place for all our high res images. The first step was setting up a google account that could hold them all and that almost ready. That being said, tracking down photos on our end it tough right now so anything you have access to, please take advantage of.

**Comment by kelseyfriedman** [comment]
Hi Julia, 

Adding my additional notes to this thread so we can QA this all at once. These are from the email I sent you back two days ago, to which you replied. 

- [ ] The Causes on Campus photos aren't all there? I'm still seeing the picture of Marcie (volunteer) on a number of those and the building one is repeated twice. You should have a different image for each in the drop box folder. 
- [ ] The CTA images are loading really slowly (and some not at all on my iPhone). Did you reduce the size before adding them? If not we need to do that and re-load them because it's slowing the site way down - lots of those are pretty high res and way bigger than needed for web. Good rule of thumb is web images should be less than 100K for large images, 50k for medium and 30k for small. We should be following these guidelines for all photos to optimize the site. 
- [ ] Some of the CTA images are causing weird breaks. I've attached screenshots so you can see what I mean. 
- [ ] Be A Volunteer CTA image on this page https://intense-spire-56347.herokuapp.com/pages/news-testimonials is the old one but on this page is the new one https://intense-spire-56347.herokuapp.com/pages/getcreative
- [ ] You noted you still owe me banner images. I assume you mean the hero images at the top? I didn't see any changes to the fuzzy images on the Our Focus page and the Volunteer page. Wasn't sure if that was part of this. Let me know if you need something specific for those or you can pull from what you have. 
- [ ] Additionally, please check the banner images on an actual mobile phone. I just looked on my iphone and none of them are resizing correctly. 
- [ ] Image/entries for causes on campus and sponsor students are not responsive on my phone. It's cutting off the sides but keeping it 2-column instead of going down to a single column

**Comment by JuliaDickey** [comment]
Ok, I resized all of the images, and replaced all of the Cause images and hero images. 

I'm not sure all of the hero images are right. I need something for The Team. The image I have just shows Ashley and I on mobile and that's a little weird. Also, do we have a good photo of ashley in the village for Our Story? I need one with more space around her so it's not so close up when it scales.

**Comment by kelseyfriedman** [comment]
I'm asking Ashley about photos of her in the village. I will ask about the team too. I don't hate the one you have there, even on mobile. But I'm sure there are photos of multiple volunteers with kids or something. 

Couple of notes
- [ ] Sponsor CTA is missing image
- [ ] Photos are broken on Our Focus page
- [ ] I will QA the causes on campus photos and Sponsor photos when pages are fixed

**Comment by JuliaDickey** [comment]
Fixed the grid on the Good Causes. Updated the Sponsor hero. I can't zoom out any more on that image, so it's a little tight, but I agree it's more impactful.

**Comment by kelseyfriedman** [comment]
Awesome! Causes page looks really good. I'm loving it! 

- [ ] I'm still not seeing an image on the Sponsor CTA? Do you need to clear your dev cache maybe? https://intense-spire-56347.herokuapp.com/pages/faq

- [ ] The photos on Our Focus in RESPONSIBLE INNOVATION are kind of fuzzy. Should we find some high res images or just remove the images from there altogether? I'm also not sure those images work with "responsible innovation" because they aren't on campus. I think we either put some campus photos or remove it altogether. I'd be fine not having images there. Your call.

**Comment by kelseyfriedman** [comment]
Sponsor CTA is still missing image? I see this on FAQ page
![screen shot 2017-03-01 at 9 55 06 am](https://cloud.githubusercontent.com/assets/3065594/23448989/3929034e-fe65-11e6-92eb-47885c2729c8.png)
