### ISSUE TITLE
Mobile menu is broken

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#47]
- [x] I can not scroll below News + Testimonials, instead it’s scrolling the page behind the menu iPhone6 Safari

- [x] on Android the menu is hidden off screen to the right

**Comment by JuliaDickey** [comment]
I'll have to check this android bug on an android device. The menu is fixed for safari mobile.

**Comment by kelseyfriedman** [comment]
- [ ]  On iPhone Safari the icons are being cut off so we need some padding at the bottom of the menu
- [ ] Faye has a new phone and the issue is still happening on Android so hopefully you can get ahold of one to troubleshoot. You have to move the screen to the right to see the menu and when you click the menu you have to scroll back left to see the words. 
![img_5034](https://cloud.githubusercontent.com/assets/3065594/23607271/46b98e20-0275-11e7-8da1-ff9b1500c729.PNG)

**Comment by JuliaDickey** [comment]
Ok, I think this is working now. I had a few friends with Android phones test it and it works. Let me know if it works for Faye's phone.

**Comment by kelseyfriedman** [comment]
Yes fixed! Good job
