### ISSUE TITLE
Remove placeholder Events

### ISSUE THREAD

**Issue by JuliaDickey** [JuliaDickey/Red-Sweater-Project-Rails#76]
-Confirm all URLs work across site

-Remove placeholder Events

**Comment by JuliaDickey** [comment]
Done

**Comment by kelseyfriedman** [comment]
I'm still seeing all the events and the images are broken too. Is the database out of sync?

**Comment by JuliaDickey** [comment]
Sorry, I had deleted them on my local database only. No, we're good. Deleting them locally deleted the images on the main database. We're synced up now.
