### ISSUE TITLE
Blog Author not updating

### ISSUE THREAD

**Issue by kelseyfriedman** [JuliaDickey/Red-Sweater-Project-Rails#89]
So I'm starting to think about not using authors on the blog posts because there are going to be times when Jordan's team writes them and it doesn't make sense to use their names (or if we write them together). 

I tried remove a name from one of my posts to see what it looked liked without an author, and while it's gone from the admin dashboard, it's still displaying on the front end. https://intense-spire-56347.herokuapp.com/blog/students-race-in-annual-kilimanjaro-5k

Also when I edited my name and just said "Kelsey" on this one https://intense-spire-56347.herokuapp.com/blog/volunteer-service-trips-improve-the-health-of-our-students-and-campus it also doesn't show a change on the front end.

**Comment by JuliaDickey** [comment]
Hmmm. There are a couple of options, and I've updated the code to allow for any of the following. 

Previously, an Author was a required field so if you remove the author, the update won't save. I removed that so you have the option of leaving the Author off of the post. 

I also had maximum character counts on the blog title and author names to keep future users from breaking the layout. The title max was set to 30 characters, which was too short for the post you were trying to update with the new author name. I upped it to 60, and removed the max char count from the Author. 

I also went in and added an if statement, so if the Author is present, it will print with the " | " in front of it. If not, only the date will show in that section. That way, it still looks great either way. 

In the admin portal, updates are done using AJAX, so if you're curious whether it properly saved to the database, refresh the page after updating. If it didn't, the block that shows the page will revert back to what it was before. I tested this locally and on the app, and both are now working with these updates.

**Comment by JuliaDickey** [comment]
Good catch!

**Comment by kelseyfriedman** [comment]
Sounds good. The if statement works on the /blog page but not on individual blog pages. Still seeing the pipe here https://intense-spire-56347.herokuapp.com/blog/students-race-in-annual-kilimanjaro-5k

Also, your message said the title max is 60 but on the admin db it says "POST TITLE (MAX 55 CHAR.)"

**Comment by JuliaDickey** [comment]
I've added it to the individual blog pages, and updated the form to say MAX 60 CHAR.
